/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.shell.view;

/**
 *
 * @author weslley rocha
 */
public class CadastroProdutoView extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroProdutoView
     */
    public CadastroProdutoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_validade = new javax.swing.JTextField();
        txt_nomeProduto = new javax.swing.JTextField();
        lbl_nomeProduto = new javax.swing.JLabel();
        lbl_Codigo = new javax.swing.JLabel();
        txt_codigo = new javax.swing.JTextField();
        lbl_quantidade = new javax.swing.JLabel();
        txt_quantidade = new javax.swing.JTextField();
        lbl_precoUnitario = new javax.swing.JLabel();
        txt_precoUnitario = new javax.swing.JTextField();
        lbl_validade = new javax.swing.JLabel();
        jb_limpar_Produto = new javax.swing.JButton();
        jb_salvarProduto = new javax.swing.JButton();

        setClosable(true);

        txt_nomeProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nomeProdutoActionPerformed(evt);
            }
        });

        lbl_nomeProduto.setText("Nome");

        lbl_Codigo.setText("Código");

        lbl_quantidade.setText("Quantidade");

        lbl_precoUnitario.setText("Preço Unitário");

        lbl_validade.setText("Validade");

        jb_limpar_Produto.setText("Limpar");
        jb_limpar_Produto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_limpar_ProdutoActionPerformed(evt);
            }
        });

        jb_salvarProduto.setText("Salvar");
        jb_salvarProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_salvarProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jb_limpar_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(jb_salvarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_validade, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_validade)
                    .addComponent(txt_precoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_precoUnitario)
                    .addComponent(lbl_quantidade)
                    .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_Codigo)
                    .addComponent(lbl_nomeProduto)
                    .addComponent(txt_nomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(92, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(43, Short.MAX_VALUE)
                .addComponent(lbl_Codigo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_codigo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_nomeProduto)
                .addGap(7, 7, 7)
                .addComponent(txt_nomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_quantidade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_precoUnitario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_precoUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_validade)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txt_validade, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jb_salvarProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jb_limpar_Produto, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_limpar_ProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_limpar_ProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_limpar_ProdutoActionPerformed

    private void jb_salvarProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_salvarProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jb_salvarProdutoActionPerformed

    private void txt_nomeProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nomeProdutoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nomeProdutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jb_limpar_Produto;
    private javax.swing.JButton jb_salvarProduto;
    private javax.swing.JLabel lbl_Codigo;
    private javax.swing.JLabel lbl_nomeProduto;
    private javax.swing.JLabel lbl_precoUnitario;
    private javax.swing.JLabel lbl_quantidade;
    private javax.swing.JLabel lbl_validade;
    private javax.swing.JTextField txt_codigo;
    private javax.swing.JTextField txt_nomeProduto;
    private javax.swing.JTextField txt_precoUnitario;
    private javax.swing.JTextField txt_quantidade;
    private javax.swing.JTextField txt_validade;
    // End of variables declaration//GEN-END:variables
}
